# Generated by Django 4.0.5 on 2022-08-27 14:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
