# Generated by Django 4.0.5 on 2022-06-21 10:03

import json
from django.db import migrations


def setup_test_data(apps, schema_editor):
    Place = apps.get_model('where_to_go', 'Place')
    files_names = (
        'static/places/moscow_legends.json',
        'static/places/roofs24.json'
    )
    for file_name in files_names:
        with open(file_name, 'r') as file:
            place = json.load(file)
            place_obj, _ = Place.objects.get_or_create(
                title=place['title'],
                short_description=place['description_short'],
                full_description=place['description_long'],
                longitude=float(place['coordinates']['lng']),
                latitude=float(place['coordinates']['lat']),
            )

class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0001_initial'),
    ]

    operations = [migrations.RunPython(setup_test_data)
    ]
