# Generated by Django 4.0.5 on 2022-08-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0002_alter_place_full_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
