# Generated by Django 4.0.5 on 2022-06-21 10:23
import json
import os

import requests
from city_guide.settings import IMAGES_PATH, MEDIA_PATH
from django.conf import settings
from django.db import migrations


def download_and_add_images(apps, schema_editor):
    Image = apps.get_model('where_to_go', 'Image')
    Place = apps.get_model('where_to_go', 'Place')

    files_names = (
        'static/places/moscow_legends.json',
        'static/places/roofs24.json'
    )

    image_dir = os.path.join(MEDIA_PATH, IMAGES_PATH)
    os.makedirs(image_dir, exist_ok=True)

    for file_name in files_names:
        with open(file_name, 'r') as file:
            place = json.load(file)
        place_obj = Place.objects.get(title=place['title'])

        images_urls = place['imgs']
        for num, url in enumerate(images_urls):
            response = requests.get(url)
            response.raise_for_status()

            photo_name = f'{place["title"]}_{num + 1}.jpg'
            with open(os.path.join(image_dir, photo_name), 'wb') as new_photo:
                new_photo.write(response.content)

            Image.objects.get_or_create(
                place=place_obj,
                index=num + 1,
                image=os.path.join(IMAGES_PATH, photo_name)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0002_setup_test_data'),
    ]

    operations = [
        migrations.RunPython(download_and_add_images)
    ]
