# Generated by Django 4.0.5 on 2022-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0003_add_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='index',
            field=models.SmallIntegerField(verbose_name='Порядковый номер (UNIQUE ONLY)'),
        ),
    ]
