# Generated by Django 4.0.5 on 2022-06-21 10:23
import json
from django.conf import settings
import requests
from django.db import migrations
import os

def download_and_add_images(apps, schema_editor):
    Image = apps.get_model('where_to_go', 'Image')
    Place = apps.get_model('where_to_go', 'Place')

    files_names = (
        'static/places/moscow_legends.json',
        'static/places/roofs24.json'
    )
    if not os.path.exists(settings.MEDIA_ROOT):
        os.mkdir(settings.MEDIA_ROOT)
    for file_name in files_names:
        with open(file_name, 'r') as file:
            place = json.load(file)
        place_obj = Place.objects.get(title=place['title'])
        images_urls = place['imgs']
        for num, url in enumerate(images_urls):
            print(url)
            response = requests.get(url)
            response.raise_for_status()
            photo_full_path = f'{settings.MEDIA_ROOT}/{place["title"]}_{num}.jpg'
            with open(photo_full_path, 'wb') as new_photo:
                new_photo.write(response.content)
            image, _ = Image.objects.get_or_create(
                place=place_obj,
                image=photo_full_path
            )
            print(image)

class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0003_image'),
    ]

    operations = [
        migrations.RunPython(download_and_add_images)
    ]
