# Generated by Django 4.0.5 on 2022-08-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0005_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='Порядковый номер (UNIQUE ONLY)'),
        ),
    ]
