# Generated by Django 4.0.5 on 2022-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0006_alter_image_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id']},
        ),
    ]
