# Generated by Django 4.0.5 on 2022-08-19 12:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0007_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='full_description',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
    ]
